services:
  - type: web
    name: invitation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn invitation.app:app --config invitation/gunicorn_config.py --capture-output --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: MAKE_WEBHOOK_URL
        value: https://hook.us1.make.com/hz3fzz8mba7sn4se4rl4klo55qbjd1j8 